FROM golang:1.13

WORKDIR /go/src/github/cs3org/reva

RUN apt-get update
RUN apt-get install git
RUN git clone https://github.com/cs3org/reva
RUN cd reva/ && make build-revad-docker
EXPOSE 9998
EXPOSE 9999
EXPOSE 10000
ENTRYPOINT cd reva/examples/oc-phoenix && ../../cmd/revad/revad -dev-dir .